# Generated by Django 5.0.7 on 2024-09-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='コード')),
                ('email', models.CharField(max_length=255, verbose_name='説明')),
                ('password', models.CharField(max_length=32, verbose_name='パスワード')),
                ('is_admin', models.BooleanField(verbose_name='管理者か')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
