# Generated by Django 5.0.7 on 2024-08-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_comment_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='created_by',
        ),
    ]
