# Generated by Django 5.0.7 on 2024-09-07 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_remove_snippet_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
