# Generated by Django 5.0.7 on 2024-09-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_alter_snippet_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='snippets',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
